apiVersion: v1
kind: Pod
metadata:
  name: playlist-elasticsearch-pod
  labels:
    run: playlist-elasticsearch
spec:
  containers:
  - name: playlist-elasticsearch-container
    image: elasticsearch:2
    ports:
    - containerPort: 9200
      hostPort: 9200
