FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Crossvader - PlaylistService

Playlist is a service that exposes a REST API allowing consumers to search 
for a playlist for a given artist name and event date.

## Playlists Collection [/v1/playlists]

### Playlist Search [GET /v1/playlists/search{?artist_name,event_date}]

Return a Playlist with tracks and event details in JSON format.

+ Parameters

    + artist_name - Artist name
    + event_date - Event date (yyyy-mm-dd)

+ Response 200 (application/json)

        {
            "data":{
                "id":"1",
                "type":"playlists",
                "attributes":{
                    "name":"Chromeo 2017-02-18"
                },
                "relationships":{
                    "event":{
                        "data":{
                            "id":"1",
                            "type":"events"
                        }
                    },
                    "tracks":{
                        "data":[
                            {
                                "id":"2",
                                "type":"tracks"
                            },
                            {
                                "id":"3",
                                "type":"tracks"
                            },
                            {
                                "id":"1",
                                "type":"tracks"
                            }
                        ]
                    }
                }
            },
            "included":[
                {
                    "id":"1",
                    "type":"events",
                    "attributes":{
                        "name":"Los Angeles Memorial Coliseum",
                        "date":"2017-02-18"
                    }
                },
                {
                    "id":"2",
                    "type":"tracks",
                    "attributes":{
                        "spotify_identifier":"1fqsqhGgKlY63H59uqjrkx",
                        "name":"Intro",
                        "isrc":"USALX0502174",
                        "duration":68506,
                        "album_release_date":"2008-07-08",
                        "album_release_date_precision":"day"
                    }
                },
                {
                    "id":"3",
                    "type":"tracks",
                    "attributes":{
                        "spotify_identifier":"5bgYTzUDzerRFN7fp86MkQ",
                        "name":"Night By Night",
                        "isrc":"USAT21001289",
                        "duration":225400,
                        "album_release_date":"2010-09-13",
                        "album_release_date_precision":"day"
                    }
                },
                {
                    "id":"1",
                    "type":"tracks",
                    "attributes":{
                        "spotify_identifier":"0vag00JbA03l7TgG7j1AbA",
                        "name":"Hot Mess",
                        "isrc":"USAT21001287",
                        "duration":220253,
                        "album_release_date":"2010-09-13",
                        "album_release_date_precision":"day"
                    }
                }
            ]
        }