FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Crossvader - PlaylistService

Playlist is a service that exposes a REST API allowing consumers to search 
for a playlist for a given artist name and event date.

## Playlists Collection [/v1/playlists]

### Playlist Search [GET /v1/playlists/search{?artist_name,event_date}]

Return a Playlist with tracks and event details in JSON format.

+ Parameters

    + artist_name - Artist name
    + event_date - Event date (yyyy-mm-dd)

+ Response 200 (application/json)

        {
            "data":{
                "id":"1",
                "type":"playlists",
                "attributes":{
                    "name":"Chromeo 2017-02-18"
                },
                "relationships":{
                    "event":{
                        "data":{
                            "id":"1",
                            "type":"events"
                        }
                    },
                    "tracks":{
                        "data":[
                            {
                                "id":"2",
                                "type":"tracks"
                            },
                            {
                                "id":"3",
                                "type":"tracks"
                            },
                            {
                                "id":"1",
                                "type":"tracks"
                            },
                            {
                                "id":"4",
                                "type":"tracks"
                            },
                            {
                                "id":"5",
                                "type":"tracks"
                            },
                            {
                                "id":"6",
                                "type":"tracks"
                            },
                            {
                                "id":"7",
                                "type":"tracks"
                            },
                            {
                                "id":"8",
                                "type":"tracks"
                            },
                            {
                                "id":"9",
                                "type":"tracks"
                            },
                            {
                                "id":"10",
                                "type":"tracks"
                            },
                            {
                                "id":"11",
                                "type":"tracks"
                            },
                            {
                                "id":"12",
                                "type":"tracks"
                            },
                            {
                                "id":"13",
                                "type":"tracks"
                            }
                        ]
                    }
                }
            },
            "included":[
                {
                    "id":"1",
                    "type":"events",
                    "attributes":{
                        "name":"Los Angeles Memorial Coliseum",
                        "date":"2017-02-18"
                    }
                },
                {
                    "id":"2",
                    "type":"tracks",
                    "attributes":{
                        "spotify_identifier":"1fqsqhGgKlY63H59uqjrkx",
                        "name":"Intro",
                        "isrc":"USALX0502174",
                        "duration":68506,
                        "album_release_date":"2008-07-08",
                        "album_release_date_precision":"day"
                    }
                },
                {
                    "id":"3",
                    "type":"tracks",
                    "attributes":{
                        "spotify_identifier":"5bgYTzUDzerRFN7fp86MkQ",
                        "name":"Night By Night",
                        "isrc":"USAT21001289",
                        "duration":225400,
                        "album_release_date":"2010-09-13",
                        "album_release_date_precision":"day"
                    }
                },
                {
                    "id":"1",
                    "type":"tracks",
                    "attributes":{
                        "spotify_identifier":"0vag00JbA03l7TgG7j1AbA",
                        "name":"Hot Mess",
                        "isrc":"USAT21001287",
                        "duration":220253,
                        "album_release_date":"2010-09-13",
                        "album_release_date_precision":"day"
                    }
                },
                {
                    "id":"4",
                    "type":"tracks",
                    "attributes":{
                        "spotify_identifier":"29T6HQEYLAc8syLr3I4SRK",
                        "name":"Somethingood",
                        "isrc":"USAT21400505",
                        "duration":390880,
                        "album_release_date":"2014-05-12",
                        "album_release_date_precision":"day"
                    }
                },
                {
                    "id":"5",
                    "type":"tracks",
                    "attributes":{
                        "spotify_identifier":"0AMHzLmyKocliVa4t6iZ5R",
                        "name":"Tenderoni",
                        "isrc":"USALX0502175",
                        "duration":254626,
                        "album_release_date":"2008-07-08",
                        "album_release_date_precision":"day"
                    }
                },
                {
                    "id":"6",
                    "type":"tracks",
                    "attributes":{
                        "spotify_identifier":"4rh7wySe2iEyEDEEzstKkt",
                        "name":"Come Alive (feat. Toro Y Moi)",
                        "isrc":"USAT21304637",
                        "duration":238680,
                        "album_release_date":"2014-05-12",
                        "album_release_date_precision":"day"
                    }
                },
                {
                    "id":"7",
                    "type":"tracks",
                    "attributes":{
                        "spotify_identifier":"2si03bj1f2F4X0Hyy0yCPx",
                        "name":"Bonafied Lovin (+ Tough Guys Interlude)",
                        "isrc":"USALX0502177",
                        "duration":272493,
                        "album_release_date":"2008-07-08",
                        "album_release_date_precision":"day"
                    }
                },
                {
                    "id":"8",
                    "type":"tracks",
                    "attributes":{
                        "spotify_identifier":"6JAGNA8nEhp6FHQlS1LzGt",
                        "name":"Sexy Socialite",
                        "isrc":"USAT21400706",
                        "duration":336160,
                        "album_release_date":"2014-05-12",
                        "album_release_date_precision":"day"
                    }
                },
                {
                    "id":"9",
                    "type":"tracks",
                    "attributes":{
                        "spotify_identifier":"5JpOCHGH1Wq1RFSLJteufN",
                        "name":"Over Your Shoulder",
                        "isrc":"USAT21302777",
                        "duration":272146,
                        "album_release_date":"2014-05-12",
                        "album_release_date_precision":"day"
                    }
                },
                {
                    "id":"10",
                    "type":"tracks",
                    "attributes":{
                        "spotify_identifier":"3tynLfCMPGbkMKLm9p960T",
                        "name":"Old 45's",
                        "isrc":"USAT21400504",
                        "duration":227906,
                        "album_release_date":"2014-05-12",
                        "album_release_date_precision":"day"
                    }
                },
                {
                    "id":"11",
                    "type":"tracks",
                    "attributes":{
                        "spotify_identifier":"3iJXQLjred9oEE5fXm8scK",
                        "name":"Fancy Footwork",
                        "isrc":"USALX0502176",
                        "duration":198106,
                        "album_release_date":"2008-07-08",
                        "album_release_date_precision":"day"
                    }
                },
                {
                    "id":"12",
                    "type":"tracks",
                    "attributes":{
                        "spotify_identifier":"3R5FA1Ay1NxgtwbElR78by",
                        "name":"Jealous (I Ain't With It)",
                        "isrc":"USAT21302779",
                        "duration":228026,
                        "album_release_date":"2014-05-12",
                        "album_release_date_precision":"day"
                    }
                },
                {
                    "id":"13",
                    "type":"tracks",
                    "attributes":{
                        "spotify_identifier":"6cbrhtNNtXBnakm6XUjWPt",
                        "name":"Fall Back 2U",
                        "isrc":"USAT21400507",
                        "duration":350413,
                        "album_release_date":"2014-05-12",
                        "album_release_date_precision":"day"
                    }
                }
            ]
        }