# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94ad938174967b6fc0669a89757daeea4b73e016d62e23ee4d5812617c2a0fa3ffcf421ec4bf68613a4f6d564497b009c031cf2587067c2252fdbbd5b806ce28

test:
  secret_key_base: 27759f8db923eb3426f9eb2b859a930a232ada2145f60cc248b13a2eadefc82db4a7403c08f33fa67aea129b8c96508f4a26469b8224cf6c868b93c447937524

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
